name: petloc01
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.18.0  # Versão mais compatível com outros pacotes
  firebase_database: ^10.5.7  # Versão compatível com o firebase_core ^2.18.0
  firebase_auth: ^4.17.4
  firebase_storage: ^11.0.0
  image_picker: ^0.8.6+3
  cloud_firestore: ^4.15.0

 

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
