// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8TIOBdXHCjN-vqgZqUw3rW-F8H7448Mc',
    appId: '1:220287525807:web:312ec49d329f6c925e855a',
    messagingSenderId: '220287525807',
    projectId: 'pet-loc-project',
    authDomain: 'pet-loc-project.firebaseapp.com',
    storageBucket: 'pet-loc-project.firebasestorage.app',
    measurementId: 'G-G7J4630RC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3GKlT-LYXVAf4aInf19NDkQLABsAeUZE',
    appId: '1:220287525807:android:1b192dad52a022025e855a',
    messagingSenderId: '220287525807',
    projectId: 'pet-loc-project',
    storageBucket: 'pet-loc-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdM7Mlji2ifD2nA62MrM-5irYEWxX2Alg',
    appId: '1:220287525807:ios:25cd1f80b7dee9ef5e855a',
    messagingSenderId: '220287525807',
    projectId: 'pet-loc-project',
    storageBucket: 'pet-loc-project.firebasestorage.app',
    iosBundleId: 'com.example.petloc01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdM7Mlji2ifD2nA62MrM-5irYEWxX2Alg',
    appId: '1:220287525807:ios:25cd1f80b7dee9ef5e855a',
    messagingSenderId: '220287525807',
    projectId: 'pet-loc-project',
    storageBucket: 'pet-loc-project.firebasestorage.app',
    iosBundleId: 'com.example.petloc01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8TIOBdXHCjN-vqgZqUw3rW-F8H7448Mc',
    appId: '1:220287525807:web:8976fcc5d3de27075e855a',
    messagingSenderId: '220287525807',
    projectId: 'pet-loc-project',
    authDomain: 'pet-loc-project.firebaseapp.com',
    storageBucket: 'pet-loc-project.firebasestorage.app',
    measurementId: 'G-T6N0NDD0QT',
  );
}
